/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
export namespace Components {
    interface AppRoot {
    }
    interface AppTabs {
    }
    interface DiscoverComponent {
    }
    interface LoginComponent {
    }
    interface MessagesComponent {
    }
    interface PageHome {
    }
    interface PageNotes {
        "name": string;
    }
    interface PageProfile {
        "name": string;
    }
    interface RegisterComponent {
    }
}
declare global {
    interface HTMLAppRootElement extends Components.AppRoot, HTMLStencilElement {
    }
    var HTMLAppRootElement: {
        prototype: HTMLAppRootElement;
        new (): HTMLAppRootElement;
    };
    interface HTMLAppTabsElement extends Components.AppTabs, HTMLStencilElement {
    }
    var HTMLAppTabsElement: {
        prototype: HTMLAppTabsElement;
        new (): HTMLAppTabsElement;
    };
    interface HTMLDiscoverComponentElement extends Components.DiscoverComponent, HTMLStencilElement {
    }
    var HTMLDiscoverComponentElement: {
        prototype: HTMLDiscoverComponentElement;
        new (): HTMLDiscoverComponentElement;
    };
    interface HTMLLoginComponentElement extends Components.LoginComponent, HTMLStencilElement {
    }
    var HTMLLoginComponentElement: {
        prototype: HTMLLoginComponentElement;
        new (): HTMLLoginComponentElement;
    };
    interface HTMLMessagesComponentElement extends Components.MessagesComponent, HTMLStencilElement {
    }
    var HTMLMessagesComponentElement: {
        prototype: HTMLMessagesComponentElement;
        new (): HTMLMessagesComponentElement;
    };
    interface HTMLPageHomeElement extends Components.PageHome, HTMLStencilElement {
    }
    var HTMLPageHomeElement: {
        prototype: HTMLPageHomeElement;
        new (): HTMLPageHomeElement;
    };
    interface HTMLPageNotesElement extends Components.PageNotes, HTMLStencilElement {
    }
    var HTMLPageNotesElement: {
        prototype: HTMLPageNotesElement;
        new (): HTMLPageNotesElement;
    };
    interface HTMLPageProfileElement extends Components.PageProfile, HTMLStencilElement {
    }
    var HTMLPageProfileElement: {
        prototype: HTMLPageProfileElement;
        new (): HTMLPageProfileElement;
    };
    interface HTMLRegisterComponentElement extends Components.RegisterComponent, HTMLStencilElement {
    }
    var HTMLRegisterComponentElement: {
        prototype: HTMLRegisterComponentElement;
        new (): HTMLRegisterComponentElement;
    };
    interface HTMLElementTagNameMap {
        "app-root": HTMLAppRootElement;
        "app-tabs": HTMLAppTabsElement;
        "discover-component": HTMLDiscoverComponentElement;
        "login-component": HTMLLoginComponentElement;
        "messages-component": HTMLMessagesComponentElement;
        "page-home": HTMLPageHomeElement;
        "page-notes": HTMLPageNotesElement;
        "page-profile": HTMLPageProfileElement;
        "register-component": HTMLRegisterComponentElement;
    }
}
declare namespace LocalJSX {
    interface AppRoot {
    }
    interface AppTabs {
    }
    interface DiscoverComponent {
    }
    interface LoginComponent {
    }
    interface MessagesComponent {
    }
    interface PageHome {
    }
    interface PageNotes {
        "name"?: string;
    }
    interface PageProfile {
        "name"?: string;
    }
    interface RegisterComponent {
    }
    interface IntrinsicElements {
        "app-root": AppRoot;
        "app-tabs": AppTabs;
        "discover-component": DiscoverComponent;
        "login-component": LoginComponent;
        "messages-component": MessagesComponent;
        "page-home": PageHome;
        "page-notes": PageNotes;
        "page-profile": PageProfile;
        "register-component": RegisterComponent;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "app-root": LocalJSX.AppRoot & JSXBase.HTMLAttributes<HTMLAppRootElement>;
            "app-tabs": LocalJSX.AppTabs & JSXBase.HTMLAttributes<HTMLAppTabsElement>;
            "discover-component": LocalJSX.DiscoverComponent & JSXBase.HTMLAttributes<HTMLDiscoverComponentElement>;
            "login-component": LocalJSX.LoginComponent & JSXBase.HTMLAttributes<HTMLLoginComponentElement>;
            "messages-component": LocalJSX.MessagesComponent & JSXBase.HTMLAttributes<HTMLMessagesComponentElement>;
            "page-home": LocalJSX.PageHome & JSXBase.HTMLAttributes<HTMLPageHomeElement>;
            "page-notes": LocalJSX.PageNotes & JSXBase.HTMLAttributes<HTMLPageNotesElement>;
            "page-profile": LocalJSX.PageProfile & JSXBase.HTMLAttributes<HTMLPageProfileElement>;
            "register-component": LocalJSX.RegisterComponent & JSXBase.HTMLAttributes<HTMLRegisterComponentElement>;
        }
    }
}
